### ISSUE TITLE
Crash on iOS 12 or below

### ISSUE THREAD

**Issue by michaeldimoudis** [nmilcoff/IOSSecuritySuite#1]
Hi, I added this to my app and then started to get emails of the app no longer launching on some devices. The iOS version was 12, I have an old iPhone 6 on iOS 11 were I replicated the issue and got a stack trace below. Cheers.

```
Hardware Model:      iPhone7,2
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd [1]
OS Version:          iPhone OS 11.4.1 (15G77)

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Description: DYLD, Library not loaded: @rpath/libswiftCore.dylib | Referenced from: /private/var/containers/Bundle/Application/1B69320B-F9D3-46C1-BCE3-3C1E076C9774/MyApp.app/Frameworks/IOSSecuritySuite.framework/IOSSecuritySuite | Reason: image not found
Triggered by Thread:  0

Filtered syslog:
None found

Thread 0 Crashed:
0   dyld                              0x0000000103d3a2f8 __abort_with_payload + 8
1   dyld                              0x0000000103d39ad0 abort_with_payload_wrapper_internal + 100
2   dyld                              0x0000000103d39afc fcntl + 0
3   dyld                              0x0000000103d10314 dyld::fastBindLazySymbol+ 17172 (ImageLoader**, unsigned long) + 0
4   dyld                              0x0000000103d134cc dyld::_main+ 29900 (macho_header const*, unsigned long, int, char const**, char const**, char const**, unsigned long*) + 7152
5   dyld                              0x0000000103d0d21c _dyld_start + 68

Binary Images:
0x100ebc000 - 0x103617fff MyApp arm64  <857a74446ecf3bd894ba83091fd970ba> /var/containers/Bundle/Application/1B69320B-F9D3-46C1-BCE3-3C1E076C9774/MyApp.app/MyApp
0x1039b0000 - 0x1039bbfff IOSSecuritySuite arm64  <b329fa5507d132ea80b401ab90c52fe9> /var/containers/Bundle/Application/1B69320B-F9D3-46C1-BCE3-3C1E076C9774/MyApp.app/Frameworks/IOSSecuritySuite.framework/IOSSecuritySuite
0x103d0c000 - 0x103d47fff dyld arm64  <b15e536a710732dabfafece44c5685e4> /usr/lib/dyld
```

**Comment by nmilcoff** [comment]
Hi Michael, apologies for the delay on this, I missed the notification.

Can you please add this package to your project and see if that fixes it? https://www.nuget.org/packages/Xamarin.iOS.SwiftRuntimeSupport

**Comment by michaeldimoudis** [comment]
> Can you please add this package to your project and see if that fixes it? [nuget.org/packages/Xamarin.iOS.SwiftRuntimeSupport](https://www.nuget.org/packages/Xamarin.iOS.SwiftRuntimeSupport)

Hi, just tried again and this didn't fix it (already had that package before too). So same error... 🤔

**Comment by nmilcoff** [comment]
Strange... Can you please try to run the Test app in your old iPhone? I can't reproduce it so far

**Comment by michaeldimoudis** [comment]
Ok I think the issue is because the iOS version is less than 12.2 as mentioned here https://docs.microsoft.com/en-us/xamarin/ios/platform/binding-swift/#consume-the-xamarin-binding-library some extra steps are required.

Thanks for looking into this for me.

**Comment by nmilcoff** [comment]
Yes, but the only step during the debug cycle should be adding the nuget package, as far as I understand 🤔
